# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

# Inserts a blank line between shell prompts
add_newline = true

# [character]
# success_symbol = '[âžœ](bold green)'

[docker_context]
disabled = true

[aws]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

#[python]
#disabled = true
